apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ${CERTIFICATES_CLAIM_NAME}
  namespace: '${NAMESPACE@microservice-config}'
  labels:
    moduleid: microservice-realm
    version: 1.70.0-master
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "100Mi"
  selector:
    matchLabels:
      service: "${CERTIFICATES_CRONJOB_NAME}"
