apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ${CLAIM_NAME}
  namespace: '${NAMESPACE@microservice-config}'
  labels:
    moduleid: microservice-realm
    version: 1.70.0-master
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
