apiVersion: v1
kind: Secret
metadata:
  name: ${CERTBOT_SECRET_NAME}
  namespace: ${NAMESPACE@microservice-config}
  labels:
    moduleid: microservice-realm
    version: 1.70.0-master
data:
  aws.key.id: "-"
  aws.secret.key: "-"
