apiVersion: "v1"
kind: "PersistentVolume"
metadata:
  name: "${CERTIFICATES_VOLUME_NAME}"
  namespace: ${NAMESPACE@microservice-config}
  labels:
    service: ${CERTIFICATES_CRONJOB_NAME}
    moduleid: microservice-realm
    version: 1.70.0-master
spec:
  capacity:
    storage: "1Gi"
  accessModes:
    - "ReadWriteOnce"
  awsElasticBlockStore:
    fsType: "ext4"
    volumeID: "vol-0572afea6012336e3"
