apiVersion: "v1"
kind: "PersistentVolume"
metadata:
  name: "${CERTIFICATES_VOLUME_NAME}"
  namespace: ${NAMESPACE@microservice-config}
  labels:
    service: ${CERTIFICATES_CRONJOB_NAME}
    moduleid: microservice-realm
    version: 1.70.0-master
    fsOwner: "1000"
    fsGroup: "1000"
    fsMode: "770"
spec:
  capacity:
    storage: "100Mi"
  accessModes:
    - "ReadWriteOnce"
  storageClassName: local-storage
  hostPath:
    path: /home/docker/production/${HOST@microservice-config}/volumes/${CERTIFICATES_VOLUME_NAME}
